def advent_of_code8a() -> int:
    return 0

if __name__ == "__main__":

    tst_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

    tst_output = advent_of_code8a(tst_input)
    assert tst_output==14

    with open("../data/advent_of_code6/puzzle_input.txt", "r") as f:
        puzzle_input = f.read()

    puzzle_output = advent_of_code8a(puzzle_input)
    print(f"puzzle_output of aoc8a is: {puzzle_output}")

